basepath=$(dirname $(realpath $0))

# Set fpath for autoloading
fpath=("$basepath/autoload"
       "$basepath/$([ "$WSL_DISTRO_NAME" ] && echo wsl || echo unix)"
       $fpath)

# Execute the subfiles
for f in options.zsh utils.zsh hooks.zsh; do
    source "$basepath/$f"
done

unset basepath

